Add exceptions management
Domraider/rxnet-jsonrpc pull request #3
Opened 2017-10-30 15:32 UTC by Th3Mouk

2017-10-30 16:17 UTC, etienneroudeix commented
please fix conflicts

2017-10-30 16:37 UTC, Th3Mouk commented
@etienneroudeix ✅

2017-10-31 09:12 UTC, etienneroudeix requested changes

2017-10-31 09:12 UTC, etienneroudeix commented on src/Rxnet/JsonRpc/Exceptions/UnexpectedServerAdressException.php
> +        parent::__construct("Unexpected server address", $code, $previous);
Default string must be in default `$massage` param value

2017-10-31 09:12 UTC, etienneroudeix commented on src/Rxnet/JsonRpc/Exceptions/InvalidFormatException.php
> +    public function __construct($message = "", $code = 0, Throwable $previous = null)
Why redefining `__construct`(same as parent) ?

2017-10-31 09:12 UTC, etienneroudeix commented on src/Rxnet/JsonRpc/Exceptions/ErrorResponseException.php
> +    public function __construct($message = "", $code = 0, Throwable $previous = null)
Why redefining `__construct`(same as parent) ?

2017-10-31 09:12 UTC, etienneroudeix commented on src/Rxnet/JsonRpc/Exceptions/IncorrectResponseException.php
> +    public function __construct($message = "", $code = 0, Throwable $previous = null)
Why redefining `__construct`(same as parent) ?

2017-10-31 09:12 UTC, etienneroudeix commented on src/Rxnet/JsonRpc/Exceptions/BadStatusCodeException.php
> +    public function __construct($message = "", $code = 0, Throwable $previous = null)
Why redefining `__construct`(same as parent) ?

2017-10-31 09:12 UTC, etienneroudeix commented on src/Rxnet/JsonRpc/Exceptions/RxnetJsonRpcException.php
> +    public function __construct($message = "", $code = 0, Throwable $previous = null)
Why redefining `__construct`(same as parent) ?

2017-11-02 08:54 UTC, Th3Mouk commented
@etienneroudeix ✅

2017-11-02 09:03 UTC, etienneroudeix requested changes
please update tests in `response.spec.php`to expect specific exceptions

2017-11-02 12:13 UTC, etienneroudeix commented
please rebase `master` for ci

2019-02-11 09:10 UTC, closed without merging